package e2e

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestParseRenderScenarios_WithRequires_PreservesRoundTrip(t *testing.T) {
	t.Parallel()

	input := `# E2E Scenarios — requires-project

> Auto-generated by ` + "`/auto setup`" + `. Updated by ` + "`/auto sync`" + `.

## Project Type: CLI
## Binary: auto
## Build: go build -o auto ./cmd/auto

### S1: local-smoke — Run local-only smoke
- **Command**: ` + "`auto doctor`" + `
- **Precondition**: binary built
- **Env**: N/A
- **Expect**: exit 0
- **Verify**: exit_code(0)
- **Depends**: N/A
- **Requires**: local, docker
- **Status**: active
`

	set, err := ParseScenarios([]byte(input))
	require.NoError(t, err)
	require.Len(t, set.Scenarios, 1)
	assert.Equal(t, "local, docker", set.Scenarios[0].Requires)

	rendered, err := RenderScenarios(set)
	require.NoError(t, err)
	assert.Equal(t, input, string(rendered))
}
