package cli

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

const sampleProfileScenariosContent = `# E2E Scenarios — profile-project

> Auto-generated by ` + "`/auto setup`" + `. Updated by ` + "`/auto sync`" + `.

## Project Type: CLI
## Binary: auto

### S1: standalone-pass — Standalone scenario
- **Command**: ` + "`echo standalone`" + `
- **Precondition**: N/A
- **Env**: N/A
- **Expect**: exit 0
- **Verify**: exit_code(0)
- **Depends**: N/A
- **Status**: active

### S2: local-only — Local-only scenario
- **Command**: ` + "`exit 1`" + `
- **Precondition**: N/A
- **Env**: N/A
- **Expect**: exit 0
- **Verify**: exit_code(0)
- **Depends**: N/A
- **Requires**: db, redis
- **Status**: active
`

const sampleCapabilityScenarioContent = `# E2E Scenarios — capability-project

> Auto-generated by ` + "`/auto setup`" + `. Updated by ` + "`/auto sync`" + `.

## Project Type: CLI
## Binary: auto

### S1: docker-capability — Requires docker capability
- **Command**: ` + "`echo docker`" + `
- **Precondition**: N/A
- **Env**: N/A
- **Expect**: exit 0
- **Verify**: exit_code(0)
- **Depends**: N/A
- **Requires**: docker
- **Status**: active
`

func writeAutopusConfigFile(t *testing.T, projectDir, content string) {
	t.Helper()
	require.NoError(t, os.WriteFile(filepath.Join(projectDir, "autopus.yaml"), []byte(content), 0o644))
}

func decodeScenarioResults(t *testing.T, out []byte) []scenarioJSONResult {
	t.Helper()

	var payload struct {
		Results []scenarioJSONResult `json:"results"`
	}
	require.NoError(t, json.Unmarshal(out, &payload))
	return payload.Results
}

func TestTestRunCmd_DefaultStandalone_SkipsRequiresMismatch(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	writeScenariosFile(t, dir, sampleProfileScenariosContent)

	cmd := newAutoTestCmd()
	var out bytes.Buffer
	cmd.SetOut(&out)
	cmd.SetErr(&out)
	cmd.SetArgs([]string{"run", "--project-dir", dir, "--json"})

	err := cmd.Execute()
	require.NoError(t, err)

	results := decodeScenarioResults(t, out.Bytes())
	require.Len(t, results, 2)
	assert.Equal(t, "PASS", results[0].Status)
	assert.Equal(t, "SKIP", results[1].Status)
	assert.Contains(t, results[1].Reason, "requires")
}

func TestTestRunCmd_ProfileFlag_RunsMatchingRequires(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	writeScenariosFile(t, dir, sampleProfileScenariosContent)

	cmd := newAutoTestCmd()
	var out bytes.Buffer
	cmd.SetOut(&out)
	cmd.SetErr(&out)
	cmd.SetArgs([]string{"run", "--project-dir", dir, "--profile", "local", "--json"})

	err := cmd.Execute()
	require.NoError(t, err)

	results := decodeScenarioResults(t, out.Bytes())
	require.Len(t, results, 2)
	assert.Equal(t, "PASS", results[0].Status)
	assert.Equal(t, "FAIL", results[1].Status)
}

func TestTestRunCmd_ProfileCapabilities_FromConfig(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	writeScenariosFile(t, dir, sampleCapabilityScenarioContent)
	writeAutopusConfigFile(t, dir, `
mode: full
project_name: profile-project
platforms:
  - claude-code
architecture:
  auto_generate: true
  enforce: false
lore:
  enabled: true
spec:
  id_format: "SPEC-{DOMAIN}-{NUMBER}"
profiles:
  test:
    capabilities:
      standalone:
        - standalone
        - docker
`)

	cmd := newAutoTestCmd()
	var out bytes.Buffer
	cmd.SetOut(&out)
	cmd.SetErr(&out)
	cmd.SetArgs([]string{"run", "--project-dir", dir, "--profile", "standalone", "--json"})

	err := cmd.Execute()
	require.NoError(t, err)

	results := decodeScenarioResults(t, out.Bytes())
	require.Len(t, results, 1)
	assert.Equal(t, "PASS", results[0].Status)
}
